# mongo-express Deployment
apiVersion: apps/v1
kind: Deployment
# Part 1
metadata:
  name: mongo-express
  labels:
    app: mongo-express
# Part 2
spec: # Deployment Specification
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec: # Container Specification
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: db_host
---
# mongodb service
apiVersion: v1
kind: Service
# Part 1
metadata:
  name: mongo-express-service
# Part 2
spec: # Deployment Specification
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 #Range: 30000 - 32767
