# mongodb Deployment
apiVersion: apps/v1
kind: Deployment
# Part 1
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
# Part 2
spec: # Deployment Specification
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec: # Container Specification
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: root-password
---
# mongodb service
apiVersion: v1
kind: Service
# Part 1
metadata:
  name: mongo-service
# Part 2
spec: # Deployment Specification
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
