# Docker Secret Configuration file
apiVersion: v1
kind: Secret
# Opaque - default for arbitrary key/value pairs
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-secret

# Generate these values like ```echo -n 'username' | base64```
data:
  .dockerconfigjson: {{ "{\"auths\": {\"localhost\": {\"username\": \"docker-user\", \"password\": \"password\"}}}" | b64enc }}
